"""Discord Bot - Generated by C2B"""
from __future__ import annotations

import asyncio
import os
from pathlib import Path

import discord
from discord.ext import commands

from keep_alive import keep_alive


intents = discord.Intents.default()
intents.message_content = True
intents.guilds = True
intents.members = True

bot = commands.Bot(command_prefix="!", intents=intents)


@bot.event
async def on_ready():
    print(f"Logged in as {bot.user}")
    await bot.tree.sync()
    print("Commands synced!")


async def load_cogs() -> None:
    """Load all cogs dynamically from ./cogs"""
    cogs_dir = Path(__file__).parent / "cogs"
    if not cogs_dir.exists():
        print("No cogs/ directory found")
        return

    for path in sorted(cogs_dir.glob("*.py")):
        if path.name == "__init__.py":
            continue
        ext = f"cogs.{path.stem}"
        try:
            await bot.load_extension(ext)
            print(f"Loaded {ext}")
        except Exception as e:
            print(f"Failed to load {ext}: {e}")


async def main() -> None:
    keep_alive()
    await load_cogs()
    await bot.start(os.getenv("DISCORD_TOKEN"))


if __name__ == "__main__":
    asyncio.run(main())
